framework:
    rate_limiter:
        license_api:
            policy: sliding_window
            limit: 60
            interval: '1 minute'
        two_factor:
            policy: sliding_window
            limit: 10
            interval: '1 minute'
